# ?? BASE DE DATOS ??????????????????????????????????
spring.datasource.url=jdbc:postgresql://localhost:5432/InazumaLegacy
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Quitamos el dialecto manual (Hibernate 7 lo detecta solo)

spring.thymeleaf.cache=false

# ?? EMAIL (Gmail) ???????????????????????????????????
# IMPORTANTE: pon tu Gmail y una Contraseña de Aplicación
# (NO tu contraseña normal de Gmail)
# Cómo obtenerla:
#   1. myaccount.google.com
#   2. Seguridad ? Verificación en 2 pasos (actívala si no la tienes)
#   3. Busca "Contraseñas de aplicación" ? crea una nueva ? copia los 16 caracteres
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=victorlopezruiz@elpuig.xeill.net
spring.mail.password=gqva oahn ogcu ojdq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
# API de Claude (Anthropic)
groq.api.key=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