
# Si Railway no detecta las variables, usará por defecto los valores de Supabase que ya funcionan
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.ynpgjfalauefkvdojhlf}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Ve5blOQvs1Y2OKZ7}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optimización para el Pooler de Supabase
spring.datasource.hikari.maximum-pool-size=10


spring.thymeleaf.cache=false


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=victorlopezruiz@elpuig.xeill.net
spring.mail.password=gqva oahn ogcu ojdq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

openai.api.key=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